In [27]:
import numpy as np

### Basic array operations

In [28]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Meshgrid

In [128]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

X, Y

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [127]:

Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

### Diag

In [31]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [32]:
np.diag(np.arange(0, 10, 1))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [33]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [36]:
a[-5:-1]

array([6, 7, 8, 9])

In [37]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### From lambda

In [38]:
f = lambda m, n: n + 10 * m

In [39]:
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [40]:
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [41]:
A[1, :]

array([10, 11, 12, 13, 14, 15])

In [42]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [43]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [44]:
A[3:, 3:]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

### Linspace and dims

In [69]:
A = np.linspace(0, 1, 21)
A

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [46]:
A[np.array([0, 2, 4])]

array([0. , 0.1, 0.2])

In [47]:
A[[0, 2, 4]]

array([0. , 0.1, 0.2])

In [48]:
A[1:4]

array([0.05, 0.1 , 0.15])

In [49]:
A > 0.5

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [50]:
A[A > 0.5]

array([0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [67]:
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [64]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [68]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [76]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [75]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [73]:
data.flatten()

array([1, 2, 3, 4])

In [94]:
data = np.arange(0,5)
data

array([0, 1, 2, 3, 4])

In [81]:
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [83]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [87]:
np.expand_dims(data, axis=0)

array([[0, 1, 2, 3, 4]])

In [90]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [91]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [95]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [96]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [99]:
x = np.array([
    [1, 2],
    [3, 4]
])
y = np.array([
    [5, 6],
    [7, 8]
])
x + y

array([[ 6,  8],
       [10, 12]])

In [100]:
x * y

array([[ 5, 12],
       [21, 32]])

In [101]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [102]:
x * 2

array([[2, 4],
       [6, 8]])

In [108]:
z = np.array([[2, 4]])
z.shape

(1, 2)

In [109]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [111]:
zz = np.concatenate([z, z], axis=0)
zz

array([[2, 4],
       [2, 4]])

In [112]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [114]:
z = np.array([[2], [4]])
z.shape

(2, 1)

In [117]:
zz = np.concatenate([z, z], axis=1)
zz

array([[2, 2],
       [4, 4]])

In [121]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

### Elementwise Functions 

In [130]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [133]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [135]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2) == np.sin(x) ** 2 + np.cos(x) ** 2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

### Vectorize functions

In [139]:
def heaviside (x):
    return 1 if x > 0 else 0

heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [150]:
def heaviside (x):
    return 1 * (x > 0)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Aggregate function

In [155]:
data = np.random.normal(size=(15,15))
np.mean(data) == data.mean()

True

In [162]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [163]:
data.sum(axis=(0, 2)).shape

(10,)

In [164]:
data.sum()

20.010285435098027

In [166]:
data = np.arange(1, 10).reshape((3, 3))
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
data.sum() == 45

True

In [168]:
data.sum(axis=0)

array([12, 15, 18])

In [169]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean Arrays and Conditional Expressions

In [172]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b

array([ True,  True, False, False])

In [173]:
np.all(a < b)

False

In [174]:
np.all(a > b)

False

In [175]:
x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [176]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [177]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [180]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))
x = np.linspace(-5, 5, 11)
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [181]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [186]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [187]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [190]:
np.select([x < -1, x < 2, x >= 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [198]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [202]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8]),)

In [204]:
x[np.nonzero(abs(x) > 2)] == x[abs(x) > 2]

array([ True,  True,  True,  True])

### Set operations

In [206]:
a = np.unique([1, 2, 3, 3])
b = np.unique([2, 3, 4, 4, 5, 6, 5])

np.in1d(a, b)

array([False,  True,  True])

In [207]:
np.intersect1d(a, b)

array([2, 3])

In [208]:
np.setdiff1d(a, b)

array([1])

In [209]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [210]:
np.all(np.in1d(a, b))

False

### Operations on Arrays


In [222]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [223]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [224]:
np.fliplr(data)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [216]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

(1, 2, 3, 4, 5)

In [217]:
data.T.shape

(5, 4, 3, 2, 1)

### Matrix and vectors

In [226]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [227]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [228]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [229]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [231]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [232]:
x = np.arange(3)
x

array([0, 1, 2])

In [233]:
np.dot(A, x)

array([ 5, 14, 23])

In [234]:
A.dot(x)

array([ 5, 14, 23])

In [236]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [239]:
# Also dot product
Ap = B @ A @ np.linalg.inv(B)
Ap

array([[  5.3114273 , -11.01288152,  21.58379879],
       [  5.22902378, -10.84062845,  20.27392429],
       [  1.83569056,  -3.7521618 ,   6.78792433]])

In [241]:
A = np.matrix(A)
B = np.matrix(B)
Ap = B * A * B.I
Ap

matrix([[  5.3114273 , -11.01288152,  21.58379879],
        [  5.22902378, -10.84062845,  20.27392429],
        [  1.83569056,  -3.7521618 ,   6.78792433]])

In [242]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [243]:
np.inner(x, x) == np.dot(x, x)

True

In [244]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [246]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [247]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [248]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [249]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])