## Init deps

In [15]:
using Pkg
Pkg.add("SymPy")
Pkg.add("Test")
Pkg.add("LinearAlgebra")
Pkg.add("Plots")

using SymPy
using Test
using LinearAlgebra
using Plots
# using SymbolicUtils

include("../lib/KTBC.jl")
using .KTBC: CreateKTBC

  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


# Task \#1
### Symbol calculations

In [36]:
@vars u₁ u₂

u⁺ = [u₁ u₂]
u = [
  u₁
  u₂
]

T₂ = convert(Array{Int}, CreateKTBC(2)[2])

u⁺T₂u = u⁺ * T₂ * u


1-element Array{Sym,1}:
 u₁⋅(u₁ - u₂) + u₂⋅(-u₁ + 2⋅u₂)

#### Find the result

In [56]:
result₁ = [u₁ * (u₁ - u₂) + u₂ * (-u₁ + 2 * u₂)]

1-element Array{Sym,1}:
 u₁⋅(u₁ - u₂) + u₂⋅(-u₁ + 2⋅u₂)

### The result is:

$$u^T \cdot T₂ \cdot u = u₁^2 - 2u₁u₂ + u₂^2 $$

### Or you can see it by diff

$$u^T \cdot T₂ \cdot u - (u₁^2 - 2u₁u₂ + u₂^2) = 0 $$

#### If result is equal, difference is equal zero

In [55]:
@test u⁺T₂u[1] - result₁[1] == 0

Test Passed

# Task \#3
### Produce Circulant matrix C

In [34]:
A = [
  1 -1 0
  0 1 -1
  -1 0 1
]

3×3 Array{Int64,2}:
  1  -1   0
  0   1  -1
 -1   0   1

In [33]:
C = (A') * A

3×3 Array{Int64,2}:
  2  -1  -1
 -1   2  -1
 -1  -1   2

In [47]:
z = zeros(Int, 3)

3-element Array{Int64,1}:
 0
 0
 0

$$ 
 \begin{bmatrix}
  a_{11} \\
  a_{21} \\
  a_{31}
 \end{bmatrix} + \begin{bmatrix}
  a_{12} \\
  a_{22} \\
  a_{32}
 \end{bmatrix} + \begin{bmatrix}
  a_{13} \\
  a_{23} \\
  a_{33}
 \end{bmatrix} = \begin{bmatrix}
  0 \\
  0 \\
  0
 \end{bmatrix}
$$

In [49]:
@test A[1:3] + A[4:6] + A[7:9] == z

Test Passed

#### The same for C

$$ 
 \begin{bmatrix}
  c_{11} \\
  c_{21} \\
  c_{31}
 \end{bmatrix} + \begin{bmatrix}
  c_{12} \\
  c_{22} \\
  c_{32}
 \end{bmatrix} + \begin{bmatrix}
  c_{13} \\
  c_{23} \\
  c_{33}
 \end{bmatrix} = \begin{bmatrix}
  0 \\
  0 \\
  0
 \end{bmatrix}
$$

In [51]:
@test C[1:3] + C[4:6] + C[7:9] == z

Test Passed

#### Find the vector u

In [53]:
u = ones(Int, 3) # <- solution

@test A * u == z

Test Passed

#### C is not Positive definite for Cholesky

In [54]:
@test_throws PosDefException cholesky(C)

Test Passed
      Thrown: PosDefException